In [2]:
import random
import pyspiel
import numpy as np

In [27]:
game = pyspiel.load_game("othello")
state = game.new_initial_state()
while not state.is_terminal():
  legal_actions = state.legal_actions()
  if state.is_chance_node():
    # Sample a chance event outcome.
    outcomes_with_probs = state.chance_outcomes()
    action_list, prob_list = zip(*outcomes_with_probs)
    action = np.random.choice(action_list, p=prob_list)
    state.apply_action(action)
  else:
    # The algorithm can pick an action based on an observation (fully observable
    # games) or an information state (information available for that player)
    # We arbitrarily select the first available action as an example.
    action = legal_actions[0]
    state.apply_action(action)

In [74]:
game = pyspiel.load_game("othello")
state = game.new_initial_state()
print(state.legal_actions())
print(np.array(state.observation_tensor(1)).reshape(3, 8, 8))
# print(np.array(state.observation_tensor(0)).reshape(3, 8, 8)[1] - np.array(state.observation_tensor(0)).reshape(3, 8, 8)[2])
mboard = np.zeros(64, dtype=np.int8)
mboard[state.legal_actions()] = 1
print(mboard.reshape(8, 8))
state.current_player()

[19, 26, 37, 44]
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 0. 0. 1. 1. 1.]
  [1. 1. 1. 0. 0. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


0

In [20]:
list(map(lambda move: move.action, state.full_history()))

[19,
 18,
 17,
 9,
 1,
 0,
 26,
 2,
 10,
 11,
 3,
 4,
 8,
 16,
 37,
 12,
 5,
 6,
 64,
 13,
 64,
 20,
 64,
 33,
 25,
 32,
 24,
 34,
 40,
 29,
 21,
 22,
 14,
 15,
 7,
 23,
 31,
 30,
 42,
 38,
 39,
 41,
 50,
 43,
 44,
 45,
 46,
 47,
 55,
 48,
 64,
 49,
 56,
 51,
 52,
 53,
 54,
 62,
 57,
 58,
 59,
 60,
 61,
 63]